# Generated by Django 3.2.6 on 2024-04-06 03:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ceco',
            fields=[
                ('id_ceco', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_ceco', models.CharField(max_length=255)),
                ('presupuesto_original', models.IntegerField()),
                ('presupuesto_disponible', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id_cuentacontable', models.IntegerField(primary_key=True, serialize=False)),
                ('id_ceco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OCApp.ceco')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('rut_proveedor', models.CharField(max_length=15, unique=True)),
                ('nombre_proveedor', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('cuadro_comparativo_archivo', models.FileField(upload_to='cuadros_comparativos_pdf')),
                ('soc_archivo', models.FileField(upload_to='solicitud_orden_compra_pdf')),
                ('descripcion', models.TextField()),
                ('descripcion_operador', models.TextField(null=True)),
                ('estado', models.CharField(choices=[('Recibida', 'Recibida'), ('Asignada', 'Asignada'), ('En progreso', 'En progreso'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FechaEstado',
            fields=[
                ('id_solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='OCApp.solicitud')),
                ('fecha_recibida', models.DateTimeField(null=True)),
                ('fecha_asignada', models.DateTimeField(null=True)),
                ('fecha_en_progreso', models.DateTimeField(null=True)),
                ('fecha_finalizada', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut_usuario', models.CharField(max_length=15, unique=True)),
                ('rol', models.CharField(choices=[('Operador', 'Operador'), ('Solicitante', 'Solicitante'), ('Administrador', 'Administrador')], max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OCApp.area')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='asignado_operador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_cuentacontable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OCApp.cuentacontable'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='rut_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RegistroGasto',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('monto', models.IntegerField()),
                ('id_cuentacontable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OCApp.cuentacontable')),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OCApp.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_contacto_proveedor', models.CharField(blank=True, max_length=255)),
                ('telefono_contacto_proveedor', models.CharField(blank=True, max_length=255)),
                ('correo_contacto_proveedor', models.CharField(blank=True, max_length=255)),
                ('cotizaciones_archivo', models.FileField(null=True, upload_to='archivos_cotizaciones_pdf')),
                ('seleccionado', models.BooleanField(default=False)),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OCApp.solicitud')),
                ('rut_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OCApp.proveedor', to_field='rut_proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='id_ceco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OCApp.ceco'),
        ),
    ]
